# Generated by Django 3.1.1 on 2020-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_donations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='description',
            field=models.CharField(default='Enter donation description', max_length=1000),
        ),
    ]
