# Generated by Django 3.1.1 on 2020-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20201020_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='title_processed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
