# Generated by Django 3.1.1 on 2020-10-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donation_title_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='title_processed',
            field=models.CharField(default='default_title', max_length=100),
        ),
    ]
