# Generated by Django 3.1.1 on 2020-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_auto_20201020_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='percentage_met',
            field=models.IntegerField(default=0),
        ),
    ]
