# Generated by Django 3.1.1 on 2020-10-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_auto_20201021_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
