# Generated by Django 3.1.1 on 2020-10-29 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_auto_20201029_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 19, 19, 8, 611372), verbose_name='date donations started'),
        ),
    ]
