# Generated by Django 3.1.1 on 2020-11-09 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_auto_20201109_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 19, 12, 2, 829724), verbose_name='date donations started'),
        ),
    ]
