# Generated by Django 3.1.1 on 2020-11-12 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0016_auto_20201109_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 13, 7, 18, 975584), verbose_name='date donations started'),
        ),
    ]
