# Generated by Django 3.1.1 on 2020-11-12 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_auto_20201112_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 9, 15, 673627), verbose_name='date donations started'),
        ),
    ]
