# Generated by Django 3.1.1 on 2020-11-12 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_auto_20201112_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdonation',
            name='user',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 16, 21, 5, 798929), verbose_name='date donations started'),
        ),
    ]
