# Generated by Django 3.1.1 on 2020-11-12 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0019_auto_20201112_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 16, 29, 29, 114516), verbose_name='date donations started'),
        ),
        migrations.AlterField(
            model_name='individualdonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
