# Generated by Django 3.1.1 on 2020-11-12 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0020_auto_20201112_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdonation',
            name='title',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 21, 51, 415639), verbose_name='date donations started'),
        ),
    ]
