# Generated by Django 3.1.1 on 2020-11-13 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0021_auto_20201112_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 21, 6, 53, 538787), verbose_name='date donations started'),
        ),
    ]
