# Generated by Django 3.1.1 on 2020-11-19 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0022_auto_20201112_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 21, 8, 29, 607243), verbose_name='date donations started'),
        ),
    ]
