# Generated by Django 3.1.1 on 2020-11-19 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_auto_20201118_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='creator',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 16, 3, 25415), verbose_name='date donations started'),
        ),
    ]
