# Generated by Django 3.1.1 on 2020-11-19 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_auto_20201118_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(default='/donation/images/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 11, 36, 905342), verbose_name='date donations started'),
        ),
    ]
