# Generated by Django 3.1.1 on 2020-11-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0024_auto_20201119_1716'),
        ('donation', '0025_auto_20201119_1724'),
    ]

    operations = [
    ]
